baseURL = "/"
title = "VU Documentation"

theme = ["docsy"]

enableGitInfo = true

contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

publishdir = "dist"

[languages]
[languages.en]
title = "VU Documentation"
description = "Venice Unleashed documentation"
languageName ="English"

[params]
copyright = "Venice Unleashed"
github_repo = "https://github.com/EmulatorNexus/VU-Docs"
algolia_docsearch = false
offlineSearch = true

[params.ui.feedback]
enable = false

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "igor"