baseURL = "/"
title = "VU Docs"
description = "Venice Unleashed wiki and online documentation"

theme = ["docsy"]

enableGitInfo = true

contentDir = "content"
publishdir = "dist"


[params]
copyright = "Venice Unleashed"
github_repo = "https://github.com/EmulatorNexus/VU-Docs"
algolia_docsearch = false
offlineSearch = true

[params.ui.feedback]
enable = false

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"